In [1]:
import numpy as np


In [2]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
d=np.random.randn(2,3,4)
d

array([[[-2.36010393,  1.11194034,  1.3569775 ,  0.40439322],
        [-0.20408033, -0.62245313,  0.96174387,  1.36168339],
        [ 0.25357872, -0.94984198, -0.99307119,  1.04811707]],

       [[ 0.02222019,  1.14504292, -2.35005632, -2.41455014],
        [ 0.5861749 , -0.47030163, -1.3504972 , -1.17012524],
        [-1.28777773,  0.93533841, -2.1003405 ,  0.26873809]]])

In [4]:
X=np.array([22,35,86])
w1=np.random.randn(3,3)
w1

array([[ 1.02195018, -0.68301136, -2.08118445],
       [-0.8434431 ,  1.52948512,  0.90326009],
       [ 1.22224937,  0.71023986,  0.5135131 ]])

In [6]:
w2=np.random.randn(2,3)
y=np.dot(w2,np.dot(w1,X))
y

array([300.52421716,  36.68585912])

In [1]:
import tensorflow as tf


In [3]:
print(tf.version)

<module 'tensorflow._api.v2.version' from '/Users/hehaoyuan/opt/anaconda3/lib/python3.8/site-packages/tensorflow/_api/v2/version/__init__.py'>


In [4]:
rank_0_tensor = tf.constant(4)

In [5]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [7]:
rank_3_tensor = tf.constant(
  [[0, 1, 2, 3],
   [5, 6, 7, 8],[0, 1, 2, 3],
   [5, 6, 7, 8]])
                    
print(rank_3_tensor)

tf.Tensor(
[[0 1 2 3]
 [5 6 7 8]
 [0 1 2 3]
 [5 6 7 8]], shape=(4, 4), dtype=int32)


In [8]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [9]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [10]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


In [11]:
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())

First: 0
Second: 1
Last: 34


In [12]:
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


In [13]:
a=tf.Variable([2.0,3.0])
a.assign([1,2])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [18]:
x=tf.constant(1.0)
with tf.GradientTape() as t:
    t.watch(x)
    y=tf.multiply(x,x) +tf.exp(x)
    dy_dx = t.gradient(y,x)